org: maurobc
service: api-alumnos-rds-v2

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 20
  region: us-east-1
  iam:
    role: arn:aws:iam::546297147037:role/LabRole
  environment:
    SECRET_NAME: rds_mysql_alumnos_user_${sls:stage}  # dev, test, prod
    AWS_REGION: us-east-1

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    package:
      include:
        - ./**  # Incluir todo el contenido del directorio
    events:
      - http:
          path: /alumnos/listar
          method: get
          cors: true
